DEFAULT_ROLL_PRICE = 1

TIER_1_PET_SHOP_SIZE = 3
TIER_2_PET_SHOP_SIZE = 3
TIER_3_PET_SHOP_SIZE = 4
TIER_4_PET_SHOP_SIZE = 4
TIER_5_PET_SHOP_SIZE = 5
TIER_6_PET_SHOP_SIZE = 5

TIER_1_FOOD_SHOP_SIZE = 1
TIER_2_FOOD_SHOP_SIZE = 1
TIER_3_FOOD_SHOP_SIZE = 1
TIER_4_FOOD_SHOP_SIZE = 2
TIER_5_FOOD_SHOP_SIZE = 2
TIER_6_FOOD_SHOP_SIZE = 2

